// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GymApp.Models;

[Table("Class")]
[Index("ProgramID", Name = "IDX_Class_Program")]
public partial class Class
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public int? Capacity { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    [StringLength(20)]
    public string DayOfWeek { get; set; }

    [StringLength(255)]
    public string Image { get; set; }

    public int? ProgramID { get; set; }

    [ForeignKey("ProgramID")]
    [InverseProperty("Classes")]
    public virtual Program Program { get; set; }

    [InverseProperty("Class")]
    public virtual ICollection<Trainee> Trainees { get; set; } = new List<Trainee>();
}