// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GymApp.Models;

[Table("Coach")]
public partial class Coach
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(100)]
    public string FullName { get; set; }

    [StringLength(20)]
    public string PhoneNumber { get; set; }

    [StringLength(100)]
    public string Specialization { get; set; }

    public DateOnly? HireDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Salary { get; set; }

    public int? Experience { get; set; }

    [StringLength(255)]
    public string Image { get; set; }

    [StringLength(200)]
    public string Certification { get; set; }

    [InverseProperty("Coach")]
    public virtual ICollection<Program> Programs { get; set; } = new List<Program>();

    [InverseProperty("Coach")]
    public virtual ICollection<Trainee> Trainees { get; set; } = new List<Trainee>();
}