// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GymApp.Models;

public partial class GymManagementContext2 : IdentityDbContext<ApplicationUser>
{
    public GymManagementContext2()
    {
    }

    public GymManagementContext2(DbContextOptions<GymManagementContext2> options)
        : base(options)
    {
    }

    public virtual DbSet<Class> Classes { get; set; }

    public virtual DbSet<Coach> Coaches { get; set; }

    public virtual DbSet<DietPlan> DietPlans { get; set; }

    public virtual DbSet<InBodyTest> InBodyTests { get; set; }

    public virtual DbSet<MembershipType> MembershipTypes { get; set; }

    public virtual DbSet<Program> Programs { get; set; }

    public virtual DbSet<Trainee> Trainees { get; set; }

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-FPIMC2H\\SQLEXPRESS;Initial Catalog=GymManagement;Integrated Security=True");

    //protected override void OnModelCreating(ModelBuilder modelBuilder)
    //{
    //    modelBuilder.Entity<Class>(entity =>
    //    {
    //        entity.HasKey(e => e.ID).HasName("PK__Class__3214EC279EF0D6B6");

    //        entity.HasOne(d => d.Program).WithMany(p => p.Classes).HasConstraintName("FK__Class__ProgramID__44FF419A");
    //    });

    //    modelBuilder.Entity<Coach>(entity =>
    //    {
    //        entity.HasKey(e => e.ID).HasName("PK__Coach__3214EC27AC46CA0E");
    //    });

    //    modelBuilder.Entity<DietPlan>(entity =>
    //    {
    //        entity.HasKey(e => e.ID).HasName("PK__DietPlan__3214EC2727E6130F");

    //        entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
    //    });

    //    modelBuilder.Entity<InBodyTest>(entity =>
    //    {
    //        entity.HasKey(e => e.ID).HasName("PK__InBodyTe__3214EC273F6719C6");

    //        entity.Property(e => e.Date).HasDefaultValueSql("(CONVERT([date],getdate()))");

    //        entity.HasOne(d => d.Trainee).WithMany(p => p.InBodyTests).HasConstraintName("FK__InBodyTes__Train__48CFD27E");
    //    });

    //    modelBuilder.Entity<MembershipType>(entity =>
    //    {
    //        entity.HasKey(e => e.ID).HasName("PK__Membersh__3214EC27A1C99DD9");
    //    });

    //    modelBuilder.Entity<Program>(entity =>
    //    {
    //        entity.HasKey(e => e.ID).HasName("PK__Program__3214EC275666752F");

    //        entity.HasOne(d => d.Coach).WithMany(p => p.Programs).HasConstraintName("FK__Program__CoachID__4222D4EF");
    //    });

    //    modelBuilder.Entity<Trainee>(entity =>
    //    {
    //        entity.HasKey(e => e.ID).HasName("PK__Trainee__3214EC279E231CF1");

    //        entity.Property(e => e.Gender).IsFixedLength();
    //        entity.Property(e => e.JoinDate).HasDefaultValueSql("(CONVERT([date],getdate()))");

    //        entity.HasOne(d => d.Class).WithMany(p => p.Trainees).HasConstraintName("FK__Trainee__ClassID__4AB81AF0");

    //        entity.HasOne(d => d.Coach).WithMany(p => p.Trainees).HasConstraintName("FK__Trainee__CoachID__4BAC3F29");

    //        entity.HasOne(d => d.DietPlan).WithMany(p => p.Trainees).HasConstraintName("FK__Trainee__DietPla__49C3F6B7");

    //        entity.HasOne(d => d.MembershipType).WithMany(p => p.Trainees).HasConstraintName("FK__Trainee__Members__3F466844");
    //    });

    //    OnModelCreatingPartial(modelBuilder);
    //}

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}