// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GymApp.Models;

[Table("InBodyTest")]
[Index("TraineeID", Name = "IDX_InBodyTest_Trainee")]
public partial class InBodyTest
{
    [Key]
    public int ID { get; set; }

    public DateOnly? Date { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Height { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Weight { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Fats { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? MuscleMass { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    public int? TraineeID { get; set; }

    [ForeignKey("TraineeID")]
    [InverseProperty("InBodyTests")]
    public virtual Trainee Trainee { get; set; }
}