// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GymApp.Models;

[Table("Trainee")]
[Index("ClassID", Name = "IDX_Trainee_Class")]
[Index("CoachID", Name = "IDX_Trainee_Coach")]
[Index("DietPlanID", Name = "IDX_Trainee_DietPlan")]
[Index("MembershipTypeID", Name = "IDX_Trainee_MembershipType")]
public partial class Trainee
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(100)]
    public string FullName { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Gender { get; set; }

    public DateOnly? JoinDate { get; set; }

    public DateOnly? DOB { get; set; }

    public int? MembershipTypeID { get; set; }

    public int? DietPlanID { get; set; }

    public int? ClassID { get; set; }

    public int? CoachID { get; set; }

    [ForeignKey("ClassID")]
    [InverseProperty("Trainees")]
    public virtual Class Class { get; set; }

    [ForeignKey("CoachID")]
    [InverseProperty("Trainees")]
    public virtual Coach Coach { get; set; }

    [ForeignKey("DietPlanID")]
    [InverseProperty("Trainees")]
    public virtual DietPlan DietPlan { get; set; }

    [InverseProperty("Trainee")]
    public virtual ICollection<InBodyTest> InBodyTests { get; set; } = new List<InBodyTest>();

    [ForeignKey("MembershipTypeID")]
    [InverseProperty("Trainees")]
    public virtual MembershipType MembershipType { get; set; }
}